const LANG = {
  ja: {
    title: "🎵 TikTok Stream config.yml Generator",
    boxSettings: "🧊 BOX内部の自動変換 設定",
    top: "Top",
    middle: "Middle",
    bottom: "Bottom",
    clearCountdown: "⏳ クリアカウントダウン数設定",
    events: "🎮 イベント設定",
    noteEvents: "チェック(有効)にするとTikTokの該当イベントをMinecraftに転送できます",
    gift: "Gift",
    like: "Like",
    follow: "Follow",
    share: "Share",
    subscribe: "Subscribe",
    comment: "Comment",
    commentNote: "※ commentにチェックを入れるとMinecraftのチャット欄にリスナーのコメントが「[TikTok]【名前】{コメント内容}」のフォーマットで表示されます",
    generateYaml: "YAML生成",
    giftSettingsNonStreak: "🎁 ギフト設定（連続なし）",
    giftSettingsStreak: "🎁 ギフト設定（連続あり）｜　コマンド×連続ギフト数　のイベントになります",
    likeSettings: "❤️ Like 設定（count条件）",
    followSettings: "📢 Follow 設定",
    shareSettings: "🔁 Share 設定",
    subscribeSettings: "⭐ Subscribe 設定",
    addRule: "＋ ルール追加",
    addCommand: "＋ command",
    delete: "削除",
    commandSelect: "コマンド選択",
    streakable: "連続可",
    nonStreakable: "連続不可",
  },
  en: {
    title: "🎵 TikTok Stream config.yml Generator",
    boxSettings: "🧊 Box Auto-Replace Settings",
    top: "Top",
    middle: "Middle",
    bottom: "Bottom",
    clearCountdown: "⏳ Clear Countdown",
    events: "🎮 Events",
    noteEvents: "Check to enable Minecraft integration for TikTok events",
    gift: "Gift",
    like: "Like",
    follow: "Follow",
    share: "Share",
    subscribe: "Subscribe",
    comment: "Comment",
    commentNote: "If checked, TikTok comments are displayed in Minecraft chat as '[TikTok]【name】{comment}'",
    generateYaml: "Generate YAML",
    giftSettingsNonStreak: "🎁 Gift Settings (No Streak)",
    giftSettingsStreak: "🎁 Gift Settings (Streak) | Commands × Streak Count",
    likeSettings: "❤️ Like Settings (count condition)",
    followSettings: "📢 Follow Settings",
    shareSettings: "🔁 Share Settings",
    subscribeSettings: "⭐ Subscribe Settings",
    addRule: "＋ Add Rule",
    addCommand: "＋ Command",
    delete: "Delete",
    commandSelect: "Select Command",
    streakable: "Streakable",
    nonStreakable: "Non-Streakable",
  }
};